name: python-setup
description: Install poetry, python, and dependencies
runs:
  using: "composite"
    steps:
      - name: Install compatible python version
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install
