name: run-tests
run-name: Running pytest
on: [push]
jobs:
  setup:
    uses: ./.github/workflows/python-setup.yml
  pytest:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Run tests
        run: poetry run pytest django_project
